language: node_js
node_js:
  - 'node'
cache:
  - npm
install:
  - npm install
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_KEY
  skip_cleanup: true
  local_dir: build
  default_text_charset: 'utf-8'
  bucket: 'mkchallengemunic'
  region: us-west-1
